kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-creator
  annotations:
    configmanagement.gke.io/cluster-selector: selector-myminikube
rules:
  - apiGroups: ["batch/v1"]
    resources: ["jobs"]
    verbs:
      - "*"