---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: minikube
    configmanagement.gke.io/source-path: foo-corp/cluster/pod-creator-clusterrole.yaml
    configsync.gke.io/declared-fields: '{"f:rules":{}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: pod-creator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
