---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    configsync.gke.io/declared-version: v1
  name: fulfillmentcenters.foo-corp.com
spec:
  group: foo-corp.com
  names:
    kind: FulfillmentCenter
    plural: fulfillmentcenters
    singular: fulfillmentcenter
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              address:
                type: string
            required:
            - address
            type: object
        type: object
    served: true
    storage: false
  - name: v2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              address:
                type: string
            required:
            - address
            type: object
        type: object
    served: true
    storage: true
