---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: minikube
    configmanagement.gke.io/source-path: foo-corp/namespaces/audit/namespace.yaml
    configsync.gke.io/declared-fields: '{}'
    hnc.x-k8s.io/managed-by: configmanagement.gke.io
  labels:
    audit.tree.hnc.x-k8s.io/depth: "0"
    configsync.gke.io/declared-version: v1
  name: audit
