---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: minikube
    configmanagement.gke.io/source-path: foo-corp/namespaces/online/shipping-app-backend/shipping-dev/job-creator-rolebinding.yaml
    configsync.gke.io/declared-fields: '{"f:roleRef":{"f:apiGroup":{},"f:kind":{},"f:name":{}},"f:subjects":{}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: job-creators
  namespace: shipping-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sam@foo-corp.com
