---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    configsync.gke.io/declared-version: v1
  name: job-creator
  namespace: zoli-test
rules:
- apiGroups:
  - batch/v1
  resources:
  - jobs
  verbs:
  - '*'
